<Project>
  <ItemGroup Condition="'$(EzyPortableLicenseRoot)' != ''">
    <None Include="$(EzyPortableLicenseRoot)\**\*"
          Link="THIRD-PARTY-LICENSES\%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
    <None Include="$(EzyPortableReadme)"
          Link="PORTABLE-README.txt"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
